apiVersion: batch/v1
kind: CronJob
metadata:
  name: msg91-credit-alerter
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure